name: ciga
description: Ecommerce app for multi-vendor

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  isco_custom_widgets:
    git: https://github.com/iscojin/isco_flutter_custom_widgets.git
  badges: ^1.1.1
  bloc: ^6.0.1
  carousel_slider: ^2.2.1
  cupertino_back_gesture: ^0.0.3
  cupertino_icons: ^0.1.3
  easy_localization: ^2.3.2
  enum_to_string: ^1.0.9
  equatable: ^1.2.3
  flushbar: ^1.10.4
  flutter_bloc: ^6.0.1
  flutter_facebook_login: ^3.0.0
  flutter_html: ^1.0.2
  flutter_launcher_icons: ^0.7.5
  flutter_phoenix: ^0.1.0
  flutter_rating_bar: ^3.2.0+1
  flutter_spinkit: ^4.1.2+1
  flutter_staggered_animations: ^0.1.2
  flutter_svg: ^0.18.1
  flutter_swiper: ^1.1.6
  font_awesome_flutter: ^8.8.1
  geolocator: ^6.1.5
  go_sell_sdk_flutter: ^2.0.3
  google_fonts: ^1.1.0
  google_maps_flutter: ^0.5.33
  google_sign_in: ^4.5.6
  image_cropper: ^1.3.1
  image_picker: ^0.6.7+7
  intl_phone_number_input: ^0.4.6+2
  lottie: ^0.6.0
  meta: ^1.1.8
  photo_view: ^0.10.2
  progress_dialog: ^1.2.4
  pull_to_refresh: ^1.6.2
  share: ^0.6.5
  shared_preferences: ^0.5.12+4
  shimmer: ^1.1.2
  sign_in_with_apple: ^2.5.4
  sliding_sheet: ^0.3.7
  sliding_up_panel: ^1.0.2
  smooth_page_indicator: ^0.2.0
  string_validator: ^0.1.4
  url_launcher: ^5.7.2
  zoom_widget: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  dio: ^3.0.10
  provider: ^4.3.2+1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/public/launcher/app-launcher-icon.png"

flutter:

  uses-material-design: true

  assets:
    - lib/public/languages/
    - lib/public/images/
    - lib/public/images/flags/
    - lib/public/images/loading/
    - lib/public/icons/
    - lib/public/animations/
    - lib/public/launcher/

  fonts:
    - family: AvenirMedium
      fonts:
        - asset: lib/public/fonts/Avenir-Medium.ttf
    - family: AvenirBook
      fonts:
        - asset: lib/public/fonts/Avenir-Book.ttf
    - family: AvenirBlack
      fonts:
        - asset: lib/public/fonts/Avenir-Black.ttf
